import '../styles/globals.scss';
import type { AppProps } from 'next/app';
import { Layout } from '../components';
import Head from 'next/head';
import { ChakraProvider } from '@chakra-ui/react';
import { theme } from '../lib/themes';
import { Fonts } from 'components/Fonts';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Birger Martin Alcanar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Fonts />
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ChakraProvider>
    </>
  );
}

export default MyApp;
